id: d214eb1eefcc49479698e7125cfda64b
initial_creation_type: ocr
source_metadata:
  volumes:
    82b85db54b9c470996501881d9a48ef3:
      base_file: v026.txt
      image_group_id: I1PD95871
      title: ཕྱག་རྒྱ་བཞི་གཏན་ལ་དབབ་པ།
      total_pages: 1902
      volume_number: 26
